version: 2.1

orbs:
  win: sandbox/windows-tools@dev:preview

workflows:
  build:
    jobs:
      - build

jobs:
    build:
        #executor: win/preview-default
        docker:
            - image: mcr.microsoft.com/dotnet/framework/sdk:4.8
        steps:
            - checkout
            #- run:
            #    name: Install DotNet
            #    command: dotnet-install.ps1
            - run:
                name: Restore packages
                command: dotnet restore
                shell: cmd.exe
            - run:
                name: Build TestingFrameworkApp
                command: dotnet build --configuration Release
            - persist_to_workspace:
                root: ~/
                paths:
                    - .nuget
                    - app