version: 2.1

orbs:
  win: sandbox/windows-tools@dev:preview

workflows:
  build:
    jobs:
      - build

jobs:
    build:
        executor: win/preview-default
        #docker:
        #    - image: mcr.microsoft.com/dotnet/framework/sdk:4.8
        steps:
            - checkout
            - run:
                name: dir
                command: dir
                shell: cmd.exe
            - run:
                name: install script
                command: |
                    .\dotnet-install.ps1
                    echo "$env:PATH"
                shell: powershell.exe
            #- run: 
            #    name: install framework
            #    command: choco install netfx-4.8-devpack --pre
            #- run:
            #    name: Install DotNet
            #    command: dotnet-install.ps1
            - run:
                name: Restore packages
                command: |
                    cd "C:\Users\circleci\AppData\Local\Microsoft\dotnet"
                    dotnet restore
                shell: powershell.exe
            - run:
                name: Build TestingFrameworkApp
                command: dotnet build --configuration Release
            - persist_to_workspace:
                root: ~/
                paths:
                    - .nuget
                    - app